name: dynaa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.0 
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.3.4
  camera: ^0.9.4+3
  flutter_tesseract_ocr: 
  image_picker: ^0.8.4+4
  mobile_scanner: ^6.0.2
  google_ml_kit: ^0.19.0
  custom_clippers: ^2.0.0
  flutter_custom_clippers: ^2.1.0
  simple_animations: ^5.1.0
  animated_icon: ^0.0.9
  animated_text_kit: ^4.2.2
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  ionicons: ^0.2.2
  standard_searchbar: ^2.1.1
  advanced_search: ^2.2.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
      - assets/
      - assets/backg.jpeg
  uses-material-design: true

